name: Expo CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # or the version specified in your project

    - name: Install dependencies
      run: npm install

    - name: Install Expo CLI
      run: npm install -g expo-cli

    - name: Run Expo Build for Android
      run: expo build:android
      env:
        EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }} # Secure your Expo CLI password

    - name: Run Expo Build for iOS
      run: expo build:ios
      env:
        EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }} # Secure your Expo CLI password

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: expo-build-artifacts
        path: |
          android/app/build/outputs/apk/release/*.apk
          ios/build/*.ipa

    - name: Clean up
      run: expo logout # Optional: Clean up Expo CLI session
